"""Capa de acceso a datos del CRM (PostgreSQL en Supabase).

La base vive fuera de la app para que los datos sobrevivan a los reinicios de
Streamlit Community Cloud, cuyo disco se borra cada vez que la app se duerme.

Todas las fechas se guardan como texto ISO 'YYYY-MM-DD' para que las
comparaciones y los ordenamientos funcionen directamente en SQL (el último
acceso de cada usuario lleva además la hora: 'YYYY-MM-DD HH:MM').
"""

import hashlib
import hmac
import secrets
from datetime import date, datetime, timedelta
from pathlib import Path

import psycopg
from psycopg.rows import dict_row

# Fecha de modificación de este archivo al cargarlo; app.py la compara para
# saber si el módulo en memoria quedó viejo tras una actualización del código.
MTIME_CARGA = Path(__file__).stat().st_mtime

ESTADOS = ["Negociación", "Cliente Activo", "Inactivo"]
TIPOS = ["Cliente", "Suplidor"]
TIPOS_CONTACTO = ["Llamada", "Email", "Reunión", "WhatsApp", "Visita"]
RESULTADOS = [
    "Interesado",
    "Pendiente de respuesta",
    "Cotización enviada",
    "Venta cerrada",
    "No interesado",
    "Sin respuesta",
]

DIAS_SIN_CONTACTO = 7

# Días desde el último contacto (o desde el alta, si nunca se contactó) hasta
# el próximo seguimiento, según tipo y estado.
DIAS_SEGUIMIENTO = {
    "Cliente": {"Negociación": 3, "Cliente Activo": 14, "Inactivo": 60},
    "Suplidor": {"Negociación": 7, "Cliente Activo": 30, "Inactivo": 90},
}

# El resultado del último contacto manda sobre la tabla anterior. Los que no
# aparecen aquí ("Venta cerrada") usan los días del tipo y estado.
DIAS_POR_RESULTADO = {
    "Cotización enviada": 2,
    "Interesado": 3,
    "Pendiente de respuesta": 3,
    "Sin respuesta": 3,
    "No interesado": 60,
}

ADMIN = "Administrador"
ROLES = [ADMIN, "Usuario"]
LARGO_MIN_CONTRASENA = 8

# PBKDF2 de la biblioteca estándar: sin dependencias nuevas. Las iteraciones se
# guardan junto a cada hash, así que subirlas más adelante no invalida las
# contraseñas ya guardadas.
ITERACIONES_HASH = 600_000


# --------------------------------------------------------------------------
# Conexión e inicialización
# --------------------------------------------------------------------------

def get_conn(url):
    """Conexión a PostgreSQL a partir de la URL de Supabase.

    autocommit: cada consulta suelta se confirma sola y las lecturas no dejan
    transacciones abiertas; las escrituras de varios pasos usan
    `conn.transaction()`. prepare_threshold=None porque el pooler de Supabase
    en modo transacción no admite sentencias preparadas.
    """
    return psycopg.connect(
        url, autocommit=True, row_factory=dict_row, prepare_threshold=None
    )


def conexion_viva(conn):
    """True si la conexión sigue respondiendo. Supabase corta las conexiones
    inactivas, y la app deja la suya abierta entre visitas."""
    if conn.closed:
        return False
    try:
        conn.execute("SELECT 1")
        return True
    except psycopg.Error:
        return False


def init_db(conn):
    with conn.transaction():
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS clientes (
                id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nombre              TEXT NOT NULL,
                empresa             TEXT,
                telefono            TEXT,
                email               TEXT,
                ubicacion           TEXT,
                giro_negocio        TEXT,
                productos_interes   TEXT,
                estado              TEXT NOT NULL DEFAULT 'Negociación',
                tipo                TEXT NOT NULL DEFAULT 'Cliente',
                fecha_creacion      TEXT NOT NULL,
                proximo_seguimiento TEXT
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS contactos (
                id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                cliente_id    INTEGER NOT NULL REFERENCES clientes (id) ON DELETE CASCADE,
                fecha         TEXT NOT NULL,
                tipo_contacto TEXT NOT NULL,
                notas         TEXT,
                resultado     TEXT
            )
            """
        )
        conn.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_contactos_cliente
                ON contactos (cliente_id, fecha DESC)
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS usuarios (
                id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                usuario         TEXT NOT NULL,
                nombre          TEXT NOT NULL,
                contrasena_hash TEXT NOT NULL,
                rol             TEXT NOT NULL DEFAULT 'Usuario',
                activo          INTEGER NOT NULL DEFAULT 1,
                fecha_creacion  TEXT NOT NULL,
                ultimo_acceso   TEXT
            )
            """
        )
        # Nombre de usuario único sin distinguir mayúsculas.
        conn.execute(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS idx_usuarios_usuario
                ON usuarios (LOWER(usuario))
            """
        )

        # El seguimiento ya no se fija a mano: los registros que quedaron sin
        # fecha reciben la calculada.
        for row in conn.execute(
            "SELECT id FROM clientes WHERE proximo_seguimiento IS NULL OR proximo_seguimiento = ''"
        ).fetchall():
            recalcular_seguimiento(conn, row["id"])


# --------------------------------------------------------------------------
# Clientes
# --------------------------------------------------------------------------

def crear_cliente(conn, datos):
    with conn.transaction():
        nuevo_id = conn.execute(
            """
            INSERT INTO clientes (nombre, empresa, telefono, email, ubicacion,
                                  productos_interes, estado, tipo, fecha_creacion)
            VALUES (%(nombre)s, %(empresa)s, %(telefono)s, %(email)s, %(ubicacion)s,
                    %(productos_interes)s, %(estado)s, %(tipo)s, %(fecha_creacion)s)
            RETURNING id
            """,
            {**datos, "fecha_creacion": date.today().isoformat()},
        ).fetchone()["id"]
        recalcular_seguimiento(conn, nuevo_id)
    return nuevo_id


def actualizar_cliente(conn, cliente_id, datos):
    """Guarda los datos del registro.

    El seguimiento solo se recalcula si cambia el tipo o el estado; corregir un
    teléfono no debe deshacer un seguimiento pospuesto a mano.
    """
    with conn.transaction():
        antes = obtener_cliente(conn, cliente_id)
        conn.execute(
            """
            UPDATE clientes
               SET nombre = %(nombre)s, empresa = %(empresa)s, telefono = %(telefono)s,
                   email = %(email)s, ubicacion = %(ubicacion)s,
                   productos_interes = %(productos_interes)s, estado = %(estado)s,
                   tipo = %(tipo)s
             WHERE id = %(id)s
            """,
            {**datos, "id": cliente_id},
        )
        if (antes["tipo"], antes["estado"]) != (datos["tipo"], datos["estado"]):
            recalcular_seguimiento(conn, cliente_id)


def eliminar_cliente(conn, cliente_id):
    """Elimina el cliente y, en cascada, todo su historial de contactos."""
    conn.execute("DELETE FROM clientes WHERE id = %s", (cliente_id,))


def obtener_cliente(conn, cliente_id):
    return conn.execute("SELECT * FROM clientes WHERE id = %s", (cliente_id,)).fetchone()


def listar_clientes(conn, busqueda="", estado="Todos", tipo="Ambos"):
    """Lista suplidores y clientes con su último contacto y total de contactos.

    La búsqueda cubre nombre, empresa, ubicación y productos de interés, sin
    distinguir mayúsculas. `tipo` filtra por "Cliente" o "Suplidor"; "Ambos"
    no filtra.
    """
    sql = """
        SELECT c.*,
               MAX(ct.fecha)                     AS ultimo_contacto,
               COUNT(ct.id)                      AS total_contactos
          FROM clientes c
          LEFT JOIN contactos ct ON ct.cliente_id = c.id
         WHERE 1 = 1
    """
    params = {}

    if busqueda:
        sql += """
             AND (c.nombre ILIKE %(q)s OR c.empresa ILIKE %(q)s
                  OR c.ubicacion ILIKE %(q)s OR c.productos_interes ILIKE %(q)s)
        """
        params["q"] = f"%{busqueda}%"

    if estado and estado != "Todos":
        sql += " AND c.estado = %(estado)s"
        params["estado"] = estado

    if tipo and tipo != "Ambos":
        sql += " AND c.tipo = %(tipo)s"
        params["tipo"] = tipo

    sql += " GROUP BY c.id ORDER BY LOWER(c.nombre)"
    return conn.execute(sql, params).fetchall()


def contar_clientes(conn):
    return conn.execute("SELECT COUNT(*) AS n FROM clientes").fetchone()["n"]


# --------------------------------------------------------------------------
# Contactos
# --------------------------------------------------------------------------

def agregar_contacto(conn, cliente_id, fecha, tipo_contacto, notas, resultado):
    """Registra el contacto y devuelve el próximo seguimiento recalculado."""
    with conn.transaction():
        conn.execute(
            """
            INSERT INTO contactos (cliente_id, fecha, tipo_contacto, notas, resultado)
            VALUES (%s, %s, %s, %s, %s)
            """,
            (cliente_id, fecha.isoformat(), tipo_contacto, notas, resultado),
        )
        return recalcular_seguimiento(conn, cliente_id)


def eliminar_contacto(conn, contacto_id):
    with conn.transaction():
        row = conn.execute(
            "DELETE FROM contactos WHERE id = %s RETURNING cliente_id", (contacto_id,)
        ).fetchone()
        if row:
            recalcular_seguimiento(conn, row["cliente_id"])


def listar_contactos(conn, cliente_id=None):
    sql = """
        SELECT ct.*, c.nombre AS cliente, c.empresa AS empresa
          FROM contactos ct
          JOIN clientes c ON c.id = ct.cliente_id
    """
    params = ()
    if cliente_id is not None:
        sql += " WHERE ct.cliente_id = %s"
        params = (cliente_id,)
    sql += " ORDER BY ct.fecha DESC, ct.id DESC"
    return conn.execute(sql, params).fetchall()


def dias_hasta_seguimiento(tipo, estado, ultimo_resultado=None):
    """Días entre el último contacto y el próximo seguimiento."""
    if ultimo_resultado in DIAS_POR_RESULTADO:
        return DIAS_POR_RESULTADO[ultimo_resultado]
    por_estado = DIAS_SEGUIMIENTO.get(tipo, DIAS_SEGUIMIENTO["Cliente"])
    # Estados que ya no existen (el antiguo "Prospecto") cuentan como Negociación.
    return por_estado.get(estado, por_estado["Negociación"])


def recalcular_seguimiento(conn, cliente_id):
    """Fija el próximo seguimiento a partir del último contacto (o del alta).

    Devuelve la nueva fecha, o None si el registro no existe.
    """
    cliente = conn.execute(
        "SELECT tipo, estado, fecha_creacion FROM clientes WHERE id = %s", (cliente_id,)
    ).fetchone()
    if not cliente:
        return None

    ultimo = conn.execute(
        """
        SELECT fecha, resultado FROM contactos
         WHERE cliente_id = %s
         ORDER BY fecha DESC, id DESC
         LIMIT 1
        """,
        (cliente_id,),
    ).fetchone()

    base = date.fromisoformat(ultimo["fecha"] if ultimo else cliente["fecha_creacion"])
    dias = dias_hasta_seguimiento(
        cliente["tipo"], cliente["estado"], ultimo["resultado"] if ultimo else None
    )
    nueva = base + timedelta(days=dias)
    conn.execute(
        "UPDATE clientes SET proximo_seguimiento = %s WHERE id = %s",
        (nueva.isoformat(), cliente_id),
    )
    return nueva


def fijar_proximo_seguimiento(conn, cliente_id, fecha):
    conn.execute(
        "UPDATE clientes SET proximo_seguimiento = %s WHERE id = %s",
        (fecha.isoformat() if fecha else None, cliente_id),
    )


# --------------------------------------------------------------------------
# Seguimiento y métricas
# --------------------------------------------------------------------------

def seguimientos(conn, dias_proximos=7):
    """Devuelve (vencidos, hoy, proximos) según la fecha de próximo seguimiento."""
    hoy = date.today()
    limite = (hoy + timedelta(days=dias_proximos)).isoformat()

    filas = conn.execute(
        """
        SELECT c.*, MAX(ct.fecha) AS ultimo_contacto
          FROM clientes c
          LEFT JOIN contactos ct ON ct.cliente_id = c.id
         WHERE c.proximo_seguimiento IS NOT NULL
           AND c.proximo_seguimiento <> ''
           AND c.proximo_seguimiento <= %s
         GROUP BY c.id
         ORDER BY c.proximo_seguimiento
        """,
        (limite,),
    ).fetchall()

    hoy_iso = hoy.isoformat()
    vencidos = [f for f in filas if f["proximo_seguimiento"] < hoy_iso]
    para_hoy = [f for f in filas if f["proximo_seguimiento"] == hoy_iso]
    proximos = [f for f in filas if f["proximo_seguimiento"] > hoy_iso]
    return vencidos, para_hoy, proximos


def clientes_sin_contactar(conn, dias=DIAS_SIN_CONTACTO):
    """Clientes cuyo último contacto (o alta, si nunca se les contactó)
    tiene `dias` o más de antigüedad."""
    limite = (date.today() - timedelta(days=dias)).isoformat()
    return conn.execute(
        """
        SELECT c.*,
               MAX(ct.fecha) AS ultimo_contacto,
               COUNT(ct.id)  AS total_contactos
          FROM clientes c
          LEFT JOIN contactos ct ON ct.cliente_id = c.id
         GROUP BY c.id
        HAVING COALESCE(MAX(ct.fecha), c.fecha_creacion) <= %s
         ORDER BY COALESCE(MAX(ct.fecha), c.fecha_creacion)
        """,
        (limite,),
    ).fetchall()


def metricas(conn):
    por_estado = {e: 0 for e in ESTADOS}
    for row in conn.execute("SELECT estado, COUNT(*) AS n FROM clientes GROUP BY estado"):
        por_estado[row["estado"]] = row["n"]

    total = sum(por_estado.values())
    activos = por_estado.get("Cliente Activo", 0)

    return {
        "total": total,
        "por_estado": por_estado,
        "activos": activos,
    }


# --------------------------------------------------------------------------
# Usuarios y acceso
# --------------------------------------------------------------------------

# Nunca se lee el hash fuera de este módulo.
COLUMNAS_USUARIO = "id, usuario, nombre, rol, activo, fecha_creacion, ultimo_acceso"


def hash_contrasena(contrasena, sal=None, iteraciones=ITERACIONES_HASH):
    """'pbkdf2_sha256$iteraciones$sal$hash' (sal aleatoria si no se da)."""
    sal = sal or secrets.token_hex(16)
    h = hashlib.pbkdf2_hmac("sha256", contrasena.encode(), sal.encode(), iteraciones).hex()
    return f"pbkdf2_sha256${iteraciones}${sal}${h}"


def verificar_contrasena(contrasena, guardado):
    _, iteraciones, sal, _ = guardado.split("$")
    return hmac.compare_digest(hash_contrasena(contrasena, sal, int(iteraciones)), guardado)


def contar_usuarios(conn):
    return conn.execute("SELECT COUNT(*) AS n FROM usuarios").fetchone()["n"]


def crear_usuario(conn, usuario, nombre, contrasena, rol):
    """Devuelve el id nuevo, o None si ya existe ese nombre de usuario
    (sin distinguir mayúsculas)."""
    try:
        return conn.execute(
            """
            INSERT INTO usuarios (usuario, nombre, contrasena_hash, rol, fecha_creacion)
            VALUES (%s, %s, %s, %s, %s)
            RETURNING id
            """,
            (usuario, nombre, hash_contrasena(contrasena), rol, date.today().isoformat()),
        ).fetchone()["id"]
    except psycopg.errors.UniqueViolation:
        return None


def autenticar(conn, usuario, contrasena):
    """Devuelve el usuario si las credenciales son válidas y la cuenta está
    activa; si no, None. Un acceso correcto queda registrado con fecha y hora."""
    row = conn.execute(
        "SELECT id, contrasena_hash, activo FROM usuarios WHERE LOWER(usuario) = LOWER(%s)",
        (usuario.strip(),),
    ).fetchone()
    if not row:
        # Mismo tiempo de respuesta que con un usuario real, para no delatar
        # qué nombres existen.
        hash_contrasena(contrasena)
        return None
    if not verificar_contrasena(contrasena, row["contrasena_hash"]) or not row["activo"]:
        return None
    conn.execute(
        "UPDATE usuarios SET ultimo_acceso = %s WHERE id = %s",
        (datetime.now().strftime("%Y-%m-%d %H:%M"), row["id"]),
    )
    return obtener_usuario(conn, row["id"])


def obtener_usuario(conn, usuario_id):
    return conn.execute(
        f"SELECT {COLUMNAS_USUARIO} FROM usuarios WHERE id = %s", (usuario_id,)
    ).fetchone()


def listar_usuarios(conn):
    return conn.execute(
        f"SELECT {COLUMNAS_USUARIO} FROM usuarios ORDER BY LOWER(nombre)"
    ).fetchall()


def actualizar_usuario(conn, usuario_id, nombre, rol, activo):
    conn.execute(
        "UPDATE usuarios SET nombre = %s, rol = %s, activo = %s WHERE id = %s",
        (nombre, rol, int(activo), usuario_id),
    )


def cambiar_contrasena(conn, usuario_id, contrasena):
    conn.execute(
        "UPDATE usuarios SET contrasena_hash = %s WHERE id = %s",
        (hash_contrasena(contrasena), usuario_id),
    )


def eliminar_usuario(conn, usuario_id):
    conn.execute("DELETE FROM usuarios WHERE id = %s", (usuario_id,))
