"""Capa de acceso a datos del CRM (PostgreSQL en Supabase).

La base vive fuera de la app para que los datos sobrevivan a los reinicios de
Streamlit Community Cloud, cuyo disco se borra cada vez que la app se duerme.

Todas las fechas se guardan como texto ISO 'YYYY-MM-DD' para que las
comparaciones y los ordenamientos funcionen directamente en SQL (el último
acceso de cada usuario lleva además la hora: 'YYYY-MM-DD HH:MM').
"""

import hashlib
import hmac
import json
import secrets
from datetime import date, datetime, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo

import psycopg
from psycopg.rows import dict_row

# Fecha de modificación de este archivo al cargarlo; app.py la compara para
# saber si el módulo en memoria quedó viejo tras una actualización del código.
MTIME_CARGA = Path(__file__).stat().st_mtime

# Súbelo cada vez que init_db cambie: app.py vuelve a correrlo al notar el
# cambio aunque la conexión cacheada ya existiera.
VERSION_ESQUEMA = 4

# El servidor de Streamlit Cloud corre en UTC; la hora del registro de
# actividad y del último acceso se guarda en la hora local.
ZONA_HORARIA = ZoneInfo("America/Santo_Domingo")

ESTADOS = ["Negociación", "Cliente Activo", "Inactivo"]
TIPOS = ["Cliente", "Suplidor"]
TIPOS_CONTACTO = ["Llamada", "Email", "Reunión", "WhatsApp", "Visita"]
RESULTADOS = [
    "Interesado",
    "Pendiente de respuesta",
    "Cotización enviada",
    "Venta cerrada",
    "No interesado",
    "Sin respuesta",
]

DIAS_SIN_CONTACTO = 7

# Días desde el último contacto (o desde el alta, si nunca se contactó) hasta
# el próximo seguimiento, según tipo y estado.
DIAS_SEGUIMIENTO = {
    "Cliente": {"Negociación": 3, "Cliente Activo": 14, "Inactivo": 60},
    "Suplidor": {"Negociación": 7, "Cliente Activo": 30, "Inactivo": 90},
}

# El resultado del último contacto manda sobre la tabla anterior. Los que no
# aparecen aquí ("Venta cerrada") usan los días del tipo y estado.
DIAS_POR_RESULTADO = {
    "Cotización enviada": 2,
    "Interesado": 3,
    "Pendiente de respuesta": 3,
    "Sin respuesta": 3,
    "No interesado": 60,
}

# Filtro de listar_clientes para los registros sin usuario asignado.
SIN_ASIGNAR = "sin_asignar"

ADMIN = "Administrador"
ROLES = [ADMIN, "Usuario"]
LARGO_MIN_CONTRASENA = 8

# PBKDF2 de la biblioteca estándar: sin dependencias nuevas. Las iteraciones se
# guardan junto a cada hash, así que subirlas más adelante no invalida las
# contraseñas ya guardadas.
ITERACIONES_HASH = 600_000


# --------------------------------------------------------------------------
# Conexión e inicialización
# --------------------------------------------------------------------------

def get_conn(url):
    """Conexión a PostgreSQL a partir de la URL de Supabase.

    autocommit: cada consulta suelta se confirma sola y las lecturas no dejan
    transacciones abiertas; las escrituras de varios pasos usan
    `conn.transaction()`. prepare_threshold=None porque el pooler de Supabase
    en modo transacción no admite sentencias preparadas.
    """
    return psycopg.connect(
        url, autocommit=True, row_factory=dict_row, prepare_threshold=None
    )


def conexion_viva(conn):
    """True si la conexión sigue respondiendo. Supabase corta las conexiones
    inactivas, y la app deja la suya abierta entre visitas."""
    if conn.closed:
        return False
    try:
        conn.execute("SELECT 1")
        return True
    except psycopg.Error:
        return False


def init_db(conn):
    with conn.transaction():
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS clientes (
                id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nombre              TEXT NOT NULL,
                empresa             TEXT,
                telefono            TEXT,
                email               TEXT,
                ubicacion           TEXT,
                giro_negocio        TEXT,
                productos_interes   TEXT,
                estado              TEXT NOT NULL DEFAULT 'Negociación',
                tipo                TEXT NOT NULL DEFAULT 'Cliente',
                fecha_creacion      TEXT NOT NULL,
                proximo_seguimiento TEXT
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS contactos (
                id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                cliente_id    INTEGER NOT NULL REFERENCES clientes (id) ON DELETE CASCADE,
                fecha         TEXT NOT NULL,
                tipo_contacto TEXT NOT NULL,
                notas         TEXT,
                resultado     TEXT
            )
            """
        )
        conn.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_contactos_cliente
                ON contactos (cliente_id, fecha DESC)
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS usuarios (
                id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                usuario         TEXT NOT NULL,
                nombre          TEXT NOT NULL,
                contrasena_hash TEXT NOT NULL,
                rol             TEXT NOT NULL DEFAULT 'Usuario',
                activo          INTEGER NOT NULL DEFAULT 1,
                fecha_creacion  TEXT NOT NULL,
                ultimo_acceso   TEXT
            )
            """
        )
        # Nombre de usuario único sin distinguir mayúsculas.
        conn.execute(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS idx_usuarios_usuario
                ON usuarios (LOWER(usuario))
            """
        )

        # Registro de actividad. Guarda el nombre del usuario y del registro
        # como texto, sin claves foráneas, para que la historia siga legible
        # aunque después se eliminen.
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS actividad (
                id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                fecha          TEXT NOT NULL,
                usuario_id     INTEGER,
                usuario_nombre TEXT NOT NULL,
                accion         TEXT NOT NULL,
                detalle        TEXT
            )
            """
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_actividad_fecha ON actividad (fecha DESC)"
        )

        # Usuarios responsables de cada registro (pueden ser varios). Al
        # eliminar el usuario o el registro, la asignación desaparece sola.
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS asignaciones (
                cliente_id INTEGER NOT NULL REFERENCES clientes (id) ON DELETE CASCADE,
                usuario_id INTEGER NOT NULL REFERENCES usuarios (id) ON DELETE CASCADE,
                PRIMARY KEY (cliente_id, usuario_id)
            )
            """
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_asignaciones_usuario ON asignaciones (usuario_id)"
        )
        # Antes cada registro tenía un solo usuario en `asignado_a`: se pasa a
        # la tabla nueva y se quita la columna para que no quede desfasada.
        if conn.execute(
            """
            SELECT 1 FROM information_schema.columns
             WHERE table_name = 'clientes' AND column_name = 'asignado_a'
            """
        ).fetchone():
            conn.execute(
                """
                INSERT INTO asignaciones (cliente_id, usuario_id)
                SELECT id, asignado_a FROM clientes WHERE asignado_a IS NOT NULL
                ON CONFLICT DO NOTHING
                """
            )
            conn.execute("ALTER TABLE clientes DROP COLUMN asignado_a")

        # Suplidor que atiende a cada cliente (opcional). Si se elimina el
        # suplidor, sus clientes quedan sin suplidor.
        conn.execute(
            """
            ALTER TABLE clientes ADD COLUMN IF NOT EXISTS suplidor_id INTEGER
                REFERENCES clientes (id) ON DELETE SET NULL
            """
        )

        # La cédula (o RNC) aparece en la factura.
        conn.execute("ALTER TABLE clientes ADD COLUMN IF NOT EXISTS cedula TEXT")

        # `datos` guarda en JSON todo lo que lleva la factura (cliente,
        # personas, líneas...) tal como se emitió, y `pdf` el archivo: aunque
        # después cambie la ficha del cliente, la factura se descarga igual.
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS facturas (
                id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                numero         TEXT NOT NULL UNIQUE,
                anio           INTEGER NOT NULL,
                secuencia      INTEGER NOT NULL,
                cliente_id     INTEGER REFERENCES clientes (id) ON DELETE SET NULL,
                cliente_nombre TEXT NOT NULL,
                fecha_emision  TEXT NOT NULL,
                total          DOUBLE PRECISION NOT NULL,
                datos          TEXT NOT NULL,
                pdf            BYTEA NOT NULL,
                creado_por     TEXT,
                fecha_creacion TEXT NOT NULL,
                UNIQUE (anio, secuencia)
            )
            """
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_facturas_cliente ON facturas (cliente_id, id DESC)"
        )

        # Ajustes que cambia un administrador (p. ej. el próximo número de
        # factura fijado a mano).
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS configuracion (
                clave TEXT PRIMARY KEY,
                valor TEXT NOT NULL
            )
            """
        )

        # El seguimiento ya no se fija a mano: los registros que quedaron sin
        # fecha reciben la calculada.
        for row in conn.execute(
            "SELECT id FROM clientes WHERE proximo_seguimiento IS NULL OR proximo_seguimiento = ''"
        ).fetchall():
            recalcular_seguimiento(conn, row["id"])


# --------------------------------------------------------------------------
# Clientes
# --------------------------------------------------------------------------

def crear_cliente(conn, datos):
    """`datos` lleva además `asignados` (lista de ids de usuario) y
    `suplidor_id` (None si no tiene; los suplidores nunca lo llevan)."""
    with conn.transaction():
        nuevo_id = conn.execute(
            """
            INSERT INTO clientes (nombre, empresa, telefono, email, ubicacion, cedula,
                                  productos_interes, estado, tipo, suplidor_id,
                                  fecha_creacion)
            VALUES (%(nombre)s, %(empresa)s, %(telefono)s, %(email)s, %(ubicacion)s,
                    %(cedula)s, %(productos_interes)s, %(estado)s, %(tipo)s,
                    %(suplidor_id)s, %(fecha_creacion)s)
            RETURNING id
            """,
            {**_sin_suplidor_si_no_es_cliente(datos), "fecha_creacion": date.today().isoformat()},
        ).fetchone()["id"]
        _fijar_asignados(conn, nuevo_id, datos["asignados"])
        recalcular_seguimiento(conn, nuevo_id)
    return nuevo_id


def _sin_suplidor_si_no_es_cliente(datos):
    return datos if datos["tipo"] == "Cliente" else {**datos, "suplidor_id": None}


def _fijar_asignados(conn, cliente_id, usuario_ids):
    """Deja exactamente esos usuarios asignados al registro."""
    conn.execute("DELETE FROM asignaciones WHERE cliente_id = %s", (cliente_id,))
    for uid in set(usuario_ids):
        conn.execute(
            "INSERT INTO asignaciones (cliente_id, usuario_id) VALUES (%s, %s)",
            (cliente_id, uid),
        )


def actualizar_cliente(conn, cliente_id, datos):
    """Guarda los datos del registro.

    El seguimiento solo se recalcula si cambia el tipo o el estado; corregir un
    teléfono no debe deshacer un seguimiento pospuesto a mano. Un suplidor que
    pasa a ser cliente suelta los clientes que tenía vinculados.
    """
    with conn.transaction():
        antes = obtener_cliente(conn, cliente_id)
        conn.execute(
            """
            UPDATE clientes
               SET nombre = %(nombre)s, empresa = %(empresa)s, telefono = %(telefono)s,
                   email = %(email)s, ubicacion = %(ubicacion)s, cedula = %(cedula)s,
                   productos_interes = %(productos_interes)s, estado = %(estado)s,
                   tipo = %(tipo)s, suplidor_id = %(suplidor_id)s
             WHERE id = %(id)s
            """,
            {**_sin_suplidor_si_no_es_cliente(datos), "id": cliente_id},
        )
        _fijar_asignados(conn, cliente_id, datos["asignados"])
        if antes["tipo"] == "Suplidor" and datos["tipo"] != "Suplidor":
            conn.execute(
                "UPDATE clientes SET suplidor_id = NULL WHERE suplidor_id = %s", (cliente_id,)
            )
        if (antes["tipo"], antes["estado"]) != (datos["tipo"], datos["estado"]):
            recalcular_seguimiento(conn, cliente_id)


def eliminar_cliente(conn, cliente_id):
    """Elimina el cliente y, en cascada, todo su historial de contactos."""
    conn.execute("DELETE FROM clientes WHERE id = %s", (cliente_id,))


def obtener_cliente(conn, cliente_id):
    return conn.execute("SELECT * FROM clientes WHERE id = %s", (cliente_id,)).fetchone()


# Usuarios asignados (`asignados`: ids; `asignados_nombres`: nombres en el
# mismo orden), nombre del suplidor y cuántos clientes tiene cada suplidor,
# para las consultas que los muestran. Subconsultas en vez de JOIN para no
# multiplicar las filas de contactos.
COLUMNAS_EXTRA = """
       COALESCE((SELECT array_agg(u.id ORDER BY LOWER(u.nombre))
                   FROM asignaciones a JOIN usuarios u ON u.id = a.usuario_id
                  WHERE a.cliente_id = c.id), '{}')     AS asignados,
       COALESCE((SELECT array_agg(u.nombre ORDER BY LOWER(u.nombre))
                   FROM asignaciones a JOIN usuarios u ON u.id = a.usuario_id
                  WHERE a.cliente_id = c.id), '{}')     AS asignados_nombres,
       (SELECT s.nombre FROM clientes s WHERE s.id = c.suplidor_id) AS suplidor_nombre,
       (SELECT COUNT(*) FROM clientes h WHERE h.suplidor_id = c.id) AS total_clientes
"""


def listar_clientes(conn, busqueda="", estado="Todos", tipo="Ambos", asignado=None):
    """Lista suplidores y clientes con su último contacto, total de contactos,
    usuarios asignados y suplidor (ver COLUMNAS_EXTRA).

    La búsqueda cubre nombre, empresa, ubicación y productos de interés, sin
    distinguir mayúsculas. `tipo` filtra por "Cliente" o "Suplidor"; "Ambos"
    no filtra. `asignado`: None no filtra, SIN_ASIGNAR trae los que no tienen
    usuario y un id trae los asignados a ese usuario (solo o con otros).
    """
    sql = f"""
        SELECT c.*, {COLUMNAS_EXTRA},
               MAX(ct.fecha)                     AS ultimo_contacto,
               COUNT(ct.id)                      AS total_contactos
          FROM clientes c
          LEFT JOIN contactos ct ON ct.cliente_id = c.id
         WHERE 1 = 1
    """
    params = {}

    if busqueda:
        sql += """
             AND (c.nombre ILIKE %(q)s OR c.empresa ILIKE %(q)s
                  OR c.ubicacion ILIKE %(q)s OR c.productos_interes ILIKE %(q)s)
        """
        params["q"] = f"%{busqueda}%"

    if estado and estado != "Todos":
        sql += " AND c.estado = %(estado)s"
        params["estado"] = estado

    if tipo and tipo != "Ambos":
        sql += " AND c.tipo = %(tipo)s"
        params["tipo"] = tipo

    if asignado == SIN_ASIGNAR:
        sql += " AND NOT EXISTS (SELECT 1 FROM asignaciones a WHERE a.cliente_id = c.id)"
    elif asignado is not None:
        sql += """
             AND EXISTS (SELECT 1 FROM asignaciones a
                          WHERE a.cliente_id = c.id AND a.usuario_id = %(asignado)s)
        """
        params["asignado"] = asignado

    sql += " GROUP BY c.id ORDER BY LOWER(c.nombre)"
    return conn.execute(sql, params).fetchall()


def contar_clientes(conn, tipo=None):
    if tipo is None:
        return conn.execute("SELECT COUNT(*) AS n FROM clientes").fetchone()["n"]
    return conn.execute(
        "SELECT COUNT(*) AS n FROM clientes WHERE tipo = %s", (tipo,)
    ).fetchone()["n"]


AGREGAR, QUITAR, REEMPLAZAR = "Agregar", "Quitar", "Reemplazar"


def asignar_clientes(conn, cliente_ids, usuario_ids, modo=AGREGAR):
    """Cambia en bloque los usuarios asignados a los registros.

    AGREGAR los suma a los que ya tenía cada registro, QUITAR se los retira y
    REEMPLAZAR deja solo esos (con la lista vacía quedan sin asignar).
    """
    cliente_ids, usuario_ids = list(cliente_ids), list(usuario_ids)
    with conn.transaction():
        if modo == QUITAR:
            conn.execute(
                "DELETE FROM asignaciones WHERE cliente_id = ANY(%s) AND usuario_id = ANY(%s)",
                (cliente_ids, usuario_ids),
            )
            return
        if modo == REEMPLAZAR:
            conn.execute("DELETE FROM asignaciones WHERE cliente_id = ANY(%s)", (cliente_ids,))
        conn.execute(
            """
            INSERT INTO asignaciones (cliente_id, usuario_id)
            SELECT c, u FROM unnest(%s::int[]) AS c CROSS JOIN unnest(%s::int[]) AS u
            ON CONFLICT DO NOTHING
            """,
            (cliente_ids, usuario_ids),
        )


def vincular_clientes(conn, suplidor_id, cliente_ids):
    """Deja a esos clientes, y solo a esos, con el suplidor. Un cliente que
    tenía otro suplidor pasa a este."""
    cliente_ids = list(cliente_ids)
    with conn.transaction():
        conn.execute(
            "UPDATE clientes SET suplidor_id = NULL WHERE suplidor_id = %s AND NOT id = ANY(%s)",
            (suplidor_id, cliente_ids),
        )
        conn.execute(
            "UPDATE clientes SET suplidor_id = %s WHERE id = ANY(%s) AND tipo = 'Cliente'",
            (suplidor_id, cliente_ids),
        )


# --------------------------------------------------------------------------
# Contactos
# --------------------------------------------------------------------------

def agregar_contacto(conn, cliente_id, fecha, tipo_contacto, notas, resultado):
    """Registra el contacto y devuelve el próximo seguimiento recalculado."""
    with conn.transaction():
        conn.execute(
            """
            INSERT INTO contactos (cliente_id, fecha, tipo_contacto, notas, resultado)
            VALUES (%s, %s, %s, %s, %s)
            """,
            (cliente_id, fecha.isoformat(), tipo_contacto, notas, resultado),
        )
        return recalcular_seguimiento(conn, cliente_id)


def eliminar_contacto(conn, contacto_id):
    with conn.transaction():
        row = conn.execute(
            "DELETE FROM contactos WHERE id = %s RETURNING cliente_id", (contacto_id,)
        ).fetchone()
        if row:
            recalcular_seguimiento(conn, row["cliente_id"])


def listar_contactos(conn, cliente_id=None):
    sql = """
        SELECT ct.*, c.nombre AS cliente, c.empresa AS empresa
          FROM contactos ct
          JOIN clientes c ON c.id = ct.cliente_id
    """
    params = ()
    if cliente_id is not None:
        sql += " WHERE ct.cliente_id = %s"
        params = (cliente_id,)
    sql += " ORDER BY ct.fecha DESC, ct.id DESC"
    return conn.execute(sql, params).fetchall()


def dias_hasta_seguimiento(tipo, estado, ultimo_resultado=None):
    """Días entre el último contacto y el próximo seguimiento."""
    if ultimo_resultado in DIAS_POR_RESULTADO:
        return DIAS_POR_RESULTADO[ultimo_resultado]
    por_estado = DIAS_SEGUIMIENTO.get(tipo, DIAS_SEGUIMIENTO["Cliente"])
    # Estados que ya no existen (el antiguo "Prospecto") cuentan como Negociación.
    return por_estado.get(estado, por_estado["Negociación"])


def recalcular_seguimiento(conn, cliente_id):
    """Fija el próximo seguimiento a partir del último contacto (o del alta).

    Devuelve la nueva fecha, o None si el registro no existe.
    """
    cliente = conn.execute(
        "SELECT tipo, estado, fecha_creacion FROM clientes WHERE id = %s", (cliente_id,)
    ).fetchone()
    if not cliente:
        return None

    ultimo = conn.execute(
        """
        SELECT fecha, resultado FROM contactos
         WHERE cliente_id = %s
         ORDER BY fecha DESC, id DESC
         LIMIT 1
        """,
        (cliente_id,),
    ).fetchone()

    base = date.fromisoformat(ultimo["fecha"] if ultimo else cliente["fecha_creacion"])
    dias = dias_hasta_seguimiento(
        cliente["tipo"], cliente["estado"], ultimo["resultado"] if ultimo else None
    )
    nueva = base + timedelta(days=dias)
    conn.execute(
        "UPDATE clientes SET proximo_seguimiento = %s WHERE id = %s",
        (nueva.isoformat(), cliente_id),
    )
    return nueva


def fijar_proximo_seguimiento(conn, cliente_id, fecha):
    conn.execute(
        "UPDATE clientes SET proximo_seguimiento = %s WHERE id = %s",
        (fecha.isoformat() if fecha else None, cliente_id),
    )


# --------------------------------------------------------------------------
# Seguimiento y métricas
# --------------------------------------------------------------------------

def seguimientos(conn, dias_proximos=7):
    """Devuelve (vencidos, hoy, proximos) según la fecha de próximo seguimiento."""
    hoy = date.today()
    limite = (hoy + timedelta(days=dias_proximos)).isoformat()

    filas = conn.execute(
        f"""
        SELECT c.*, {COLUMNAS_EXTRA}, MAX(ct.fecha) AS ultimo_contacto
          FROM clientes c
          LEFT JOIN contactos ct ON ct.cliente_id = c.id
         WHERE c.proximo_seguimiento IS NOT NULL
           AND c.proximo_seguimiento <> ''
           AND c.proximo_seguimiento <= %s
         GROUP BY c.id
         ORDER BY c.proximo_seguimiento
        """,
        (limite,),
    ).fetchall()

    hoy_iso = hoy.isoformat()
    vencidos = [f for f in filas if f["proximo_seguimiento"] < hoy_iso]
    para_hoy = [f for f in filas if f["proximo_seguimiento"] == hoy_iso]
    proximos = [f for f in filas if f["proximo_seguimiento"] > hoy_iso]
    return vencidos, para_hoy, proximos


def clientes_sin_contactar(conn, dias=DIAS_SIN_CONTACTO):
    """Clientes cuyo último contacto (o alta, si nunca se les contactó)
    tiene `dias` o más de antigüedad."""
    limite = (date.today() - timedelta(days=dias)).isoformat()
    return conn.execute(
        f"""
        SELECT c.*, {COLUMNAS_EXTRA},
               MAX(ct.fecha) AS ultimo_contacto,
               COUNT(ct.id)  AS total_contactos
          FROM clientes c
          LEFT JOIN contactos ct ON ct.cliente_id = c.id
         GROUP BY c.id
        HAVING COALESCE(MAX(ct.fecha), c.fecha_creacion) <= %s
         ORDER BY COALESCE(MAX(ct.fecha), c.fecha_creacion)
        """,
        (limite,),
    ).fetchall()


def metricas(conn):
    por_estado = {e: 0 for e in ESTADOS}
    for row in conn.execute("SELECT estado, COUNT(*) AS n FROM clientes GROUP BY estado"):
        por_estado[row["estado"]] = row["n"]

    total = sum(por_estado.values())
    activos = por_estado.get("Cliente Activo", 0)

    return {
        "total": total,
        "por_estado": por_estado,
        "activos": activos,
    }


# --------------------------------------------------------------------------
# Facturas
# --------------------------------------------------------------------------

PREFIJO_FACTURA = "RMG"

# Facturas hechas fuera del sistema antes de empezar a usarlo: la numeración de
# ese año sigue después de la última. RMG-2026-0001 se hizo y se envió a mano.
ULTIMA_FUERA_DEL_SISTEMA = {2026: 1}


def numero_factura(anio, secuencia):
    """(2026, 2) -> 'RMG-2026-0002'."""
    return f"{PREFIJO_FACTURA}-{anio}-{secuencia:04d}"


def _clave_numeracion(anio):
    return f"proxima_factura_{anio}"


def _secuencia_usada(conn, anio, secuencia):
    return conn.execute(
        "SELECT 1 FROM facturas WHERE anio = %s AND secuencia = %s", (anio, secuencia)
    ).fetchone() is not None


def secuencia_fijada(conn, anio):
    """Próximo número fijado a mano por un administrador, o None."""
    row = conn.execute(
        "SELECT valor FROM configuracion WHERE clave = %s", (_clave_numeracion(anio),)
    ).fetchone()
    return int(row["valor"]) if row else None


def ultima_secuencia(conn, anio):
    """Último número usado en el año, contando los emitidos fuera del sistema."""
    row = conn.execute(
        "SELECT MAX(secuencia) AS ultima FROM facturas WHERE anio = %s", (anio,)
    ).fetchone()
    return max(row["ultima"] or 0, ULTIMA_FUERA_DEL_SISTEMA.get(anio, 0))


def siguiente_secuencia(conn, anio):
    """El número fijado a mano si está libre; si no, el siguiente al último.
    La numeración vuelve a 0001 cada año."""
    fijada = secuencia_fijada(conn, anio)
    if fijada is not None and not _secuencia_usada(conn, anio, fijada):
        return fijada
    return ultima_secuencia(conn, anio) + 1


def siguiente_numero(conn, anio):
    return numero_factura(anio, siguiente_secuencia(conn, anio))


def fijar_siguiente_secuencia(conn, anio, secuencia):
    """Fija el número de la próxima factura del año. Devuelve un mensaje de
    error, o None si quedó guardado."""
    if secuencia < 1:
        return "El número debe ser 1 o mayor."
    if _secuencia_usada(conn, anio, secuencia):
        return f"La factura {numero_factura(anio, secuencia)} ya existe."
    conn.execute(
        """
        INSERT INTO configuracion (clave, valor) VALUES (%s, %s)
        ON CONFLICT (clave) DO UPDATE SET valor = EXCLUDED.valor
        """,
        (_clave_numeracion(anio), str(secuencia)),
    )
    return None


def quitar_secuencia_fijada(conn, anio):
    """Vuelve a la numeración automática (el siguiente al último)."""
    conn.execute("DELETE FROM configuracion WHERE clave = %s", (_clave_numeracion(anio),))


def crear_factura(conn, datos, generar_pdf, usuario=None):
    """Asigna el número siguiente, genera el PDF con él y guarda la factura.

    `datos` es el diccionario de la factura sin número; `generar_pdf` recibe
    ese diccionario ya numerado y devuelve los bytes del PDF. Si dos personas
    generan a la vez y chocan en el número, se reintenta con el siguiente.
    Devuelve el id de la factura.
    """
    anio = date.fromisoformat(datos["fecha_emision"]).year
    for _ in range(5):
        secuencia = siguiente_secuencia(conn, anio)
        numerada = {**datos, "numero": numero_factura(anio, secuencia)}
        pdf = generar_pdf(numerada)
        try:
            with conn.transaction():
                factura_id = conn.execute(
                    """
                    INSERT INTO facturas (numero, anio, secuencia, cliente_id, cliente_nombre,
                                          fecha_emision, total, datos, pdf, creado_por,
                                          fecha_creacion)
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                    RETURNING id
                    """,
                    (
                        numerada["numero"], anio, secuencia, numerada.get("cliente_id"),
                        numerada["cliente"]["nombre"], numerada["fecha_emision"],
                        numerada["total"], json.dumps(numerada, ensure_ascii=False), pdf,
                        usuario, ahora().strftime("%Y-%m-%d %H:%M"),
                    ),
                ).fetchone()["id"]
                # El número fijado a mano ya se usó: las siguientes vuelven a
                # ser automáticas.
                if secuencia_fijada(conn, anio) == secuencia:
                    quitar_secuencia_fijada(conn, anio)
        except psycopg.errors.UniqueViolation:
            continue
        return factura_id
    raise RuntimeError("No se pudo asignar un número de factura. Inténtalo de nuevo.")


def listar_facturas(conn, cliente_id=None):
    """Facturas sin el PDF, de la más reciente a la más antigua."""
    sql = """
        SELECT id, numero, anio, secuencia, cliente_id, cliente_nombre,
               fecha_emision, total, creado_por, fecha_creacion
          FROM facturas
    """
    params = ()
    if cliente_id is not None:
        sql += " WHERE cliente_id = %s"
        params = (cliente_id,)
    sql += " ORDER BY anio DESC, secuencia DESC"
    return conn.execute(sql, params).fetchall()


def obtener_factura(conn, factura_id):
    """La factura con su PDF y sus datos ya convertidos a diccionario."""
    factura = conn.execute("SELECT * FROM facturas WHERE id = %s", (factura_id,)).fetchone()
    if not factura:
        return None
    factura["datos"] = json.loads(factura["datos"])
    factura["pdf"] = bytes(factura["pdf"])
    return factura


def ultima_factura_cliente(conn, cliente_id):
    """Datos de la factura más reciente del cliente (para prellenar la
    siguiente), o None si nunca se le ha facturado."""
    row = conn.execute(
        "SELECT datos FROM facturas WHERE cliente_id = %s ORDER BY id DESC LIMIT 1",
        (cliente_id,),
    ).fetchone()
    return json.loads(row["datos"]) if row else None


def es_ultima_del_anio(conn, factura_id):
    """Solo la última factura de su año se puede eliminar: así la numeración
    queda seguida y la siguiente reutiliza ese número."""
    row = conn.execute(
        """
        SELECT f.secuencia = (SELECT MAX(secuencia) FROM facturas WHERE anio = f.anio) AS ultima
          FROM facturas f
         WHERE f.id = %s
        """,
        (factura_id,),
    ).fetchone()
    return bool(row and row["ultima"])


def eliminar_factura(conn, factura_id):
    """Devuelve False (sin borrar nada) si no es la última de su año."""
    if not es_ultima_del_anio(conn, factura_id):
        return False
    conn.execute("DELETE FROM facturas WHERE id = %s", (factura_id,))
    return True


def guardar_cedula(conn, cliente_id, cedula):
    conn.execute("UPDATE clientes SET cedula = %s WHERE id = %s", (cedula, cliente_id))


# --------------------------------------------------------------------------
# Usuarios y acceso
# --------------------------------------------------------------------------

# Nunca se lee el hash fuera de este módulo.
COLUMNAS_USUARIO = "id, usuario, nombre, rol, activo, fecha_creacion, ultimo_acceso"


def hash_contrasena(contrasena, sal=None, iteraciones=ITERACIONES_HASH):
    """'pbkdf2_sha256$iteraciones$sal$hash' (sal aleatoria si no se da)."""
    sal = sal or secrets.token_hex(16)
    h = hashlib.pbkdf2_hmac("sha256", contrasena.encode(), sal.encode(), iteraciones).hex()
    return f"pbkdf2_sha256${iteraciones}${sal}${h}"


def verificar_contrasena(contrasena, guardado):
    _, iteraciones, sal, _ = guardado.split("$")
    return hmac.compare_digest(hash_contrasena(contrasena, sal, int(iteraciones)), guardado)


def contar_usuarios(conn):
    return conn.execute("SELECT COUNT(*) AS n FROM usuarios").fetchone()["n"]


def crear_usuario(conn, usuario, nombre, contrasena, rol):
    """Devuelve el id nuevo, o None si ya existe ese nombre de usuario
    (sin distinguir mayúsculas)."""
    try:
        return conn.execute(
            """
            INSERT INTO usuarios (usuario, nombre, contrasena_hash, rol, fecha_creacion)
            VALUES (%s, %s, %s, %s, %s)
            RETURNING id
            """,
            (usuario, nombre, hash_contrasena(contrasena), rol, date.today().isoformat()),
        ).fetchone()["id"]
    except psycopg.errors.UniqueViolation:
        return None


def autenticar(conn, usuario, contrasena):
    """Devuelve el usuario si las credenciales son válidas y la cuenta está
    activa; si no, None. Un acceso correcto queda registrado con fecha y hora."""
    row = conn.execute(
        "SELECT id, contrasena_hash, activo FROM usuarios WHERE LOWER(usuario) = LOWER(%s)",
        (usuario.strip(),),
    ).fetchone()
    if not row:
        # Mismo tiempo de respuesta que con un usuario real, para no delatar
        # qué nombres existen.
        hash_contrasena(contrasena)
        return None
    if not verificar_contrasena(contrasena, row["contrasena_hash"]) or not row["activo"]:
        return None
    conn.execute(
        "UPDATE usuarios SET ultimo_acceso = %s WHERE id = %s",
        (ahora().strftime("%Y-%m-%d %H:%M"), row["id"]),
    )
    return obtener_usuario(conn, row["id"])


def obtener_usuario(conn, usuario_id):
    return conn.execute(
        f"SELECT {COLUMNAS_USUARIO} FROM usuarios WHERE id = %s", (usuario_id,)
    ).fetchone()


def listar_usuarios(conn):
    return conn.execute(
        f"SELECT {COLUMNAS_USUARIO} FROM usuarios ORDER BY LOWER(nombre)"
    ).fetchall()


def actualizar_usuario(conn, usuario_id, nombre, rol, activo):
    conn.execute(
        "UPDATE usuarios SET nombre = %s, rol = %s, activo = %s WHERE id = %s",
        (nombre, rol, int(activo), usuario_id),
    )


def cambiar_contrasena(conn, usuario_id, contrasena):
    conn.execute(
        "UPDATE usuarios SET contrasena_hash = %s WHERE id = %s",
        (hash_contrasena(contrasena), usuario_id),
    )


def eliminar_usuario(conn, usuario_id):
    conn.execute("DELETE FROM usuarios WHERE id = %s", (usuario_id,))


# --------------------------------------------------------------------------
# Registro de actividad
# --------------------------------------------------------------------------

def ahora():
    return datetime.now(ZONA_HORARIA)


def registrar_actividad(conn, usuario, accion, detalle=""):
    """Anota quién hizo qué. `usuario` es el dict del usuario con sesión."""
    conn.execute(
        """
        INSERT INTO actividad (fecha, usuario_id, usuario_nombre, accion, detalle)
        VALUES (%s, %s, %s, %s, %s)
        """,
        (
            ahora().strftime("%Y-%m-%d %H:%M:%S"),
            usuario["id"],
            f"{usuario['nombre']} ({usuario['usuario']})",
            accion,
            detalle,
        ),
    )


def listar_actividad(conn, desde, hasta, usuario_id=None, accion=None, limite=2000):
    """Actividad entre dos fechas (ambas incluidas), de la más reciente a la
    más antigua."""
    sql = """
        SELECT fecha, usuario_nombre, accion, detalle
          FROM actividad
         WHERE fecha >= %(desde)s AND fecha < %(hasta)s
    """
    params = {
        "desde": desde.isoformat(),
        "hasta": (hasta + timedelta(days=1)).isoformat(),
        "limite": limite,
    }
    if usuario_id is not None:
        sql += " AND usuario_id = %(usuario_id)s"
        params["usuario_id"] = usuario_id
    if accion:
        sql += " AND accion = %(accion)s"
        params["accion"] = accion
    sql += " ORDER BY fecha DESC, id DESC LIMIT %(limite)s"
    return conn.execute(sql, params).fetchall()


def acciones_registradas(conn):
    return [
        r["accion"]
        for r in conn.execute("SELECT DISTINCT accion FROM actividad ORDER BY accion")
    ]
